-- Run once in Supabase Dashboard > SQL Editor.
create table if not exists public.user_watchlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  ticker text not null check (ticker ~ '^[A-Z0-9.^-]{1,12}$'),
  created_at timestamptz not null default now(),
  unique (user_id, ticker)
);

alter table public.user_watchlists enable row level security;

drop policy if exists "Members can read their watchlist" on public.user_watchlists;
create policy "Members can read their watchlist" on public.user_watchlists
for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Members can add to their watchlist" on public.user_watchlists;
create policy "Members can add to their watchlist" on public.user_watchlists
for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "Members can remove from their watchlist" on public.user_watchlists;
create policy "Members can remove from their watchlist" on public.user_watchlists
for delete to authenticated using ((select auth.uid()) = user_id);

create index if not exists user_watchlists_user_created_idx
on public.user_watchlists (user_id, created_at desc);
