// Execute the real page script with minimal DOM and provider fixtures.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Node {constructor(){this.children=[];this.value='';this.textContent='';this.style={};this.classList={add(){},remove(){}};this.listeners={};}append(...n){this.children.push(...n)}replaceChildren(){this.children=[]}addEventListener(k,f){this.listeners[k]=f}removeAttribute(){} }
const elements=new Map(),get=id=>{if(!elements.has(id))elements.set(id,new Node());return elements.get(id)};
get('filter').value='all';let calls=0;
const context={document:{getElementById:get,createElement:()=>new Node(),body:{style:{}}},window:{addEventListener(){}},history:{pushState(){},replaceState(){}},location:{hash:'',pathname:'/swing-top100.html',search:''},URLSearchParams,Map,Set,AbortController,setTimeout,clearTimeout,performance,console,
 fetch:async url=>{calls++;const ticker=new URL(url,'https://example.test').searchParams.get('symbols');if(ticker==='TXG')return {ok:true,status:200,json:async()=>({rows:[],errors:[{ticker,message:'DATA_GAP'}]})};return {ok:true,status:200,json:async()=>({rows:[{ticker,status:ticker==='INTC'?'ENTRY':'WATCH',ready:ticker==='INTC',watch:true,recent_turn:ticker==='INTC',hull_distance_pct:ticker==='INTC'?.8:.1,bar_start_utc:'2026-10-09T16:00:00Z',daily:{watch_candidate:true,sma50_slope_pct:1,distance_sma20_pct:1,drawdown_52w_pct:10,bar_date:'2026-10-08'}}],errors:[]})};}};
vm.createContext(context);const html=require('node:child_process').execFileSync('python',['-c',"from api.radar_templates import TEMPLATES;print(TEMPLATES['top100'])"],{encoding:'utf8'});vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],context);
(async()=>{assert.equal(get('list').children.length,100);await vm.runInContext('scanAll()',context);assert.equal(calls,100);assert.equal(get('list').children.length,100);assert.equal(get('list').children[0].children[1].textContent,'INTC');assert.ok(vm.runInContext("errors.get('TXG')",context).includes('DATA_GAP'));get('q').value='INTC';vm.runInContext('render()',context);assert.equal(get('list').children.length,1);get('q').value='';get('filter').value='ready';vm.runInContext('render()',context);assert.equal(get('list').children.length,1);get('filter').value='all';vm.runInContext('render();showChart("INTC")',context);assert.ok(get('chartFrame').src.includes('tf=30m'));vm.runInContext('hideChart()',context);assert.equal(get('list').children.length,100);console.log('PASS: real page script, 100 retained after scan/error, ENTRY priority, filters, chart navigation');})().catch(e=>{console.error(e);process.exitCode=1});
